### PR TITLE
Summary of changes in revision grid for artificial commits

### PR DESCRIPTION
**Pull request by gerhardol**
Implements #4281

Show changed/new/deleted files and changed submodules

### CODE REVIEW

**Comment by drewnoakes** [comment]
Thanks Gerhard. This looks awesome.

Nice to be rid of `SubjectCount` too. That always seemed a bit special.

**Comment by gerhardol** [comment]
Thanks

I am guilty to SubjectCount. Cleaning up my own garbage.
While the count is related to the GitRevision, the artificial revisions are special and the count is a property of the current state, so it belongs to the grid.

Artificial commits is a gem in GE, but it is a pain too.

**Comment by drewnoakes** [comment]
The artificial commits are fantastic. Are they on by default, or did I turn them on? If there's an option, it should be on by default for sure.

**Comment by gerhardol** [comment]
Artificial commits are enabled by default in settings (new installations) for master. The functionality exist for a long time but I cleaned and enhanced that for 2.51.

**Pull request merged**
